### ISSUE TITLE
Tables should be inside expanding boxes

### ISSUE THREAD

**Issue by steffencruz** [macrocosm-os/prompting-api#14]
The current dashboard allows the user to collapse the boxes which gives a clean, minimalistic view. 

@LawrenceHunt I'd like to do the same, with the loss curve visible by default and the tables collapsed (except the 'Label' table at the top which shows the winner)

![image](https://github.com/macrocosm-os/prompting-api/assets/6709103/8e7d510e-117e-497d-bc1c-fe095a5ce749)

**Comment by LawrenceHunt** [comment]
Done!
