### ISSUE TITLE
Streaming API Response Produces Incomplete and Misaligned JSON Chunks

### ISSUE THREAD

**Issue by p-ferreira** [macrocosm-os/prompting-api#5]
@LawrenceHunt reported that the chunks are being split in a manner that leaves objects incomplete. One chunk ends just before the end of an object, and the next chunk contains the closing } along with the beginning of the next chunk. This results in difficulties when converting the streamed result into JavaScript objects, complicating downstream development.

**Comment by p-ferreira** [comment]
### Bug Report

### Summary

The Python and Node.js client solutions demonstrated below for streaming data from the `/chat/` chattensor endpoint both function as expected. They successfully capture streaming chunks, convert them to JSON, and save them to a file with the current date as the filename. Below are the respective scripts for both implementations. 

Data output:
- [python_client_result_2024-05-22.json](https://github.com/macrocosm-os/prompting-api/files/15408192/python_client_result_2024-05-22.json)
- [node_client_result_2024-05-22.json](https://github.com/macrocosm-os/prompting-api/files/15408193/node_client_result_2024-05-22.json)


### Description

This report details the successful implementation of both Python and Node.js clients to handle a streaming HTTP response, process each chunk as JSON, and save the results to a file. Both clients were tested and confirmed to work as expected.

### Steps to Reproduce

1. **Python Client Solution:**
    - Run the provided Python script.
    - The script should make a POST request to the chattensor URL (locally), stream the response, convert each chunk to JSON, and print each chunk.
    - The script should collect all JSON chunks into an array and save them to a file named with the current date.
2. **Node.js Client Solution:**
    - Set up the Node.js environment as instructed.
    - Run the provided JavaScript script.
    - The script should make a POST request to the specified URL, stream the response, convert each chunk to JSON, and print each chunk.
    - The script should collect all JSON chunks into an array and save them to a file named with the current date.

### Expected Results

- **Python Client:**
    - Each streamed chunk is output to the console as JSON.
    - The JSON chunks are collected into an array and saved to a file with the current date as the filename.
- **Node.js Client:**
    - Each streamed chunk is output to the console as JSON.
    - The JSON chunks are collected into an array and saved to a file with the current date as the filename.

### Actual Results

- Both Python and Node.js clients work as expected, with no discrepancies observed during testing.

### Attached Files

- **Python Client Script:**
    
    ```python
    from datetime import date
    import requests
    import json
    
    url = "http://0.0.0.0:10000/chat/"
    headers = {
        "api_key": "<ACCESS_KEY>",
        "Content-Type": "application/json"
    }
    data = {
        "k": 5,
        "timeout": 15,
        "roles": ["user"],
        "messages": ["Tell me a happy story about a rabbit and a turtle that meet on a budget cruise around Northern Ireland"]
    }
    
    def stream_request(url, headers, data):
        chunks = []
        response = requests.post(url, headers=headers, data=json.dumps(data), stream=True)
        for chunk in response.iter_content(chunk_size=None):
            if chunk:
                json_chunk = json.loads(chunk.decode('utf-8'))
                chunks.append(json_chunk)
                print(json_chunk)  # Log each chunk as it comes
        filename = f"{date.today().isoformat()}.json"
        with open(filename, 'w') as f:
            json.dump(chunks, f, indent=2)
        return chunks
    
    chunks = stream_request(url, headers, data)
    ```
    
- **Node.js Client Script:**
    
    ```jsx
    const axios = require('axios');
    const fs = require('fs');
    
    const url = "http://0.0.0.0:10000/chat/";
    const headers = {
        "api_key": "<ACCESS_KEY>",
        "Content-Type": "application/json"
    };
    const data = {
        "k": 5,
        "timeout": 15,
        "roles": ["user"],
        "messages": ["Tell me a happy story about a rabbit and a turtle that meet on a budget cruise around Northern Ireland"]
    };
    
    async function streamRequest() {
        const chunks = [];
        try {
            const response = await axios.post(url, data, {
                headers: headers,
                responseType: 'stream'
            });
    
            response.data.on('data', (chunk) => {
                const jsonChunk = JSON.parse(chunk.toString('utf8'));
                chunks.push(jsonChunk);
                console.log(jsonChunk);
            });
    
            response.data.on('end', () => {
                console.log('Streaming completed');
                const filename = `${new Date().toISOString().split('T')[0]}.json`;
                fs.writeFileSync(filename, JSON.stringify(chunks, null, 2));
                console.log(`Data saved to ${filename}`);
            });
        } catch (error) {
            console.error('Error:', error.message);
        }
    }
    
    streamRequest();
    ```
    

### Node.js Environment Setup Instructions:

1. **Install Node.js:**
    - If Node.js is not installed, install it using:
        
        ```bash
        sudo apt-get install nodejs
        sudo apt-get install npm
        ```
        
2. **Create a new project directory:**
    
    ```bash
    mkdir streaming-test
    cd streaming-test
    npm init -y
    ```
    
3. **Install necessary dependencies:**
    
    ```bash
    npm install axios
    ```
    
4. **Save the Node.js client script:** Save the provided JavaScript code in a file named `streamingRequest.js` within the project directory.
5. **Run the script:**
    
    ```bash
    node streamingRequest.js
    ```
    

### Conclusion
Both the Python and Node.js client solutions work as expected, correctly streaming, processing, and saving JSON data in structured chunks. This confirms the successful implementation and functionality of the clients and the back-end server of `/chat/` endpoint.

This suggests that the issue might be on the front-end application. My next steps will involve setting up the front-end application and replicating the issues locally, leveraging a validator on the test network.

**Comment by LawrenceHunt** [comment]
Confirmed this was a front-end issue. Many thanks for the help @p-ferreira
